[build-system]
requires = ["setuptools"]

[project]
name = "adapt_common"
version = "0.1"
authors = [
  {name = "Joseph G. Wallwork", email = "joe.wallwork@outlook.com"},
  {name = "Stephan C. Kramer"},
]
maintainers = [
  {name = "Joseph G. Wallwork", email = "joe.wallwork@outlook.com"},
  {name = "Stephan C. Kramer"},
]
description = "Common functionality of Mesh Adaptation packages for Firedrake"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["python", "meshing", "finite-element-method", "firedrake"]
classifiers = [
	"Development Status :: 4 - Beta",
	"Programming Language :: Python",
]
dependencies = [
  "numpy",
  "vtk",
]

[project.optional-dependencies]
dev = [
  "coverage",
  "parameterized",
  "pre-commit",
  "pytest",
  "ruff",
]

[project.urls]
Repository = "https://github.com/mesh-adaptation/adapt_common"

[tool.setuptools]
packages = ["adapt_common"]

[tool.setuptools.package-data]
animate = ["cxx/*.cxx"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
# Enable:  D: `pydocstyle`, PL: `pylint`, I: `isort`, W: `pycodestyle whitespace`
#          NPY: `numpy`, FLY: `flynt`, F: `pyflakes`, RUF: `ruff`
#          From flake8: "ARG", "SLF", "S", "BLE", "B", "A", "C4", "EM", "ICN",
#                       "PIE", "Q", "RSE", "SIM", "TID"
select = ["D", "PL", "I", "E", "W", "NPY", "FLY", "F", "RUF",
          "ARG", "SLF", "S", "BLE", "B", "A", "C4", "EM", "ICN", "PIE", "Q", "RSE",
          "SIM", "TID"]

# Ignore S101 (use of `assert` detected) as it is too strict.
[tool.ruff.per-file-ignores]
"adapt_common/norms.py" = ["S101"]
"test/*.py" = ["S101"]
